"""Host-side hodpy, distance-table and native PLC adapters.

No stochastic model or external I/O is imported by the matter-painting core.
"""

from __future__ import annotations

import hashlib
import importlib
import json
import subprocess
import sys
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

import h5py
import numpy as np
from scipy.interpolate import CubicSpline

HODPY_REVISION = "d303bef896fe6a92593d815f640f02865f11df60"
SPEED_OF_LIGHT_KM_S = 299792.458
PINOCCHIO_RHO_CRIT = 2.775499745e11


def file_sha256(path: str | Path) -> str:
    with Path(path).open("rb") as stream:
        # Explicit chunks also support Python 3.10.
        digest = hashlib.sha256()
        for chunk in iter(lambda: stream.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


@lru_cache(maxsize=4)
def hodpy_modules(root: str | Path) -> dict:
    """Load only upstream LF, colour and k-correction modules at a pinned revision.

    Does not import hodpy's default HOD constructor, nbodykit, MXXL mass
    functions or autogenerated target/occupation tables. Upstream stays intact.
    """

    root = Path(root).resolve()
    revision = subprocess.check_output(["git", "-C", str(root), "rev-parse", "HEAD"], text=True).strip()
    if revision != HODPY_REVISION:
        raise ValueError(f"Expected hodpy {HODPY_REVISION}, found {revision}")
    if "hodpy" in sys.modules and Path(sys.modules["hodpy"].__file__).resolve().parent.parent != root:
        raise ValueError("A different hodpy checkout is already imported")
    if str(root) not in sys.path:
        sys.path.insert(0, str(root))
    return {name: importlib.import_module(f"hodpy.{name}")
            for name in ("colour", "luminosity_function", "k_correction", "lookup")}


class IndependentLuminosityFunction:
    """Fixed observational SDSS/GAMA cumulative LF using upstream hodpy classes.

    Magnitudes are ^0.1 M_r - 5 log10(h); densities are h^3/Mpc^3. No data
    generated by a PINOCCHIO or MXXL HOD enters the target. Evolution and
    the smooth redshift transition exactly follow upstream's Target class.
    """

    def __init__(self, hodpy_root: str | Path):
        self.root = Path(hodpy_root).resolve()
        modules = hodpy_modules(self.root)
        upstream = modules["luminosity_function"]
        parameters = np.loadtxt(self.root / "lookup/lf_params.dat", delimiter=",")
        self.parameters = dict(zip(("phi_star", "m_star", "alpha", "P", "Q"), parameters, strict=True))
        self.sdss = upstream.LuminosityFunctionTabulated(
            self.root / "lookup/sdss_cumulative_lf.dat", parameters[3], parameters[4],
        )
        self.gama = upstream.LuminosityFunctionSchechter(*parameters)
        self.input_hashes = {
            name: file_sha256(self.root / name) for name in (
                "lookup/sdss_cumulative_lf.dat", "lookup/lf_params.dat", "lookup/hod_params.dat",
                "lookup/k_corr_rband_z01.dat", "hodpy/colour.py", "hodpy/luminosity_function.py",
                "hodpy/hod_bgs.py", "hodpy/k_correction.py",
            )
        }

    def cumulative(self, magnitude, redshift):
        """Number density brighter than magnitude; accepts broadcasting arrays."""
        magnitude, redshift = np.broadcast_arrays(magnitude, redshift)
        m, z = magnitude.ravel(), redshift.ravel()
        shifted = m + self.parameters["Q"]*(z-.1)
        if np.any(shifted < self.sdss.magnitude[0]) or np.any(shifted > self.sdss.magnitude[-1]):
            raise ValueError("Requested target LF is outside the supplied observational table")
        transition = 1/(1+np.exp(120*(z-.15)))
        value = transition*self.sdss.Phi_cumulative(m, z) + (1-transition)*self.gama.Phi_cumulative(m, z)
        if np.any(~np.isfinite(value)) or np.any(value <= 0):
            raise ValueError("Independent target LF returned a non-positive/non-finite density")
        return value.reshape(magnitude.shape)

    def reference_magnitude(self, magnitude, redshift):
        """Magnitude at z=0.1 of equal target number density, as in hodpy HOD_BGS."""
        grid = np.linspace(-27., -10.5, 16501)
        log_density = np.log(self.cumulative(grid, .1))
        value = np.log(self.cumulative(magnitude, redshift))
        if np.any(value < log_density[0]) or np.any(value > log_density[-1]):
            raise ValueError("LF number-density mapping is outside its reference grid")
        return np.interp(value, log_density, grid)


class PinocchioDistances:
    """Distances from the native cosmology table, not hodpy's MXXL cosmology.

    Native distances are Mpc regardless of OutputInH100. Interpolate with a
    natural cubic spline in log10(a), matching PINOCCHIO's tabulation variable.
    Only positive-distance rows are spline knots: native zero entries at a>=1
    are placeholders, not knots. Match PINOCCHIO's endpoint secant extrapolation
    below its lowest positive-redshift knot. Public distances are comoving
    Mpc/h. Volume is a flat-space cone volume in (Mpc/h)^3.
    """

    def __init__(self, path: str | Path, h: float):
        values = np.loadtxt(path)
        select = (values[:, 0] < 1.) & (values[:, 0] >= .1) & (values[:, 2] > 0)
        a = values[select, 0]
        chi = values[select, 2]*h
        order = np.argsort(a)
        a, chi = a[order], chi[order]
        if len(a) < 4 or np.any(np.diff(chi) >= 0):
            raise ValueError("Distance table needs monotone positive distances")
        self.h = float(h)
        self.zmax = 1/a[0]-1
        self._distance = CubicSpline(np.log10(a), chi, bc_type="natural", extrapolate=False)
        self._last_log_a, self._last_chi = np.log10(a[-1]), chi[-1]
        self._endpoint_slope = (chi[-1]-chi[-2])/(np.log10(a[-1])-np.log10(a[-2]))
        z = np.linspace(0., min(self.zmax, 3.), 60001)
        chi_dense = self.comoving_distance(z)
        positive = chi_dense > 0
        if np.any(np.diff(chi_dense[positive]) <= 0):
            raise ValueError("Distance interpolant is not monotone")
        self._redshift = CubicSpline(np.r_[0., chi_dense[positive]], np.r_[0., z[positive]], extrapolate=False)

    def comoving_distance(self, redshift):
        redshift = np.asarray(redshift)
        if np.any((redshift < 0) | (redshift > self.zmax)):
            raise ValueError("Redshift outside native distance table")
        log_a = -np.log10(1+redshift)
        result = np.where(log_a <= self._last_log_a, self._distance(log_a),
                          self._last_chi+(log_a-self._last_log_a)*self._endpoint_slope)
        return np.where(redshift <= 0, 0., np.maximum(result, 0.))

    def redshift(self, chi):
        value = self._redshift(chi)
        if not np.all(np.isfinite(value)):
            raise ValueError("Comoving distance outside inverse distance table")
        return value

    def volume(self, zlo: float, zhi: float, aperture_deg: float) -> float:
        omega = 2*np.pi*(1-np.cos(np.deg2rad(aperture_deg)))
        return float(omega/3*(self.comoving_distance(zhi)**3-self.comoving_distance(zlo)**3))

    def volume_average(self, function, zlo: float, zhi: float, order: int = 12):
        nodes, weights = np.polynomial.legendre.leggauss(order)
        clo, chi = self.comoving_distance(np.array([zlo, zhi]))
        radius = .5*(chi+clo)+.5*(chi-clo)*nodes
        weight = .5*(chi-clo)*weights*radius**2 / ((chi**3-clo**3)/3)
        return np.sum(function(self.redshift(radius))*weight, axis=-1)


def cone_basis(axis) -> np.ndarray:
    """Orthonormal rows (x,y,z) of PINOCCHIO's cone-aligned angular basis."""
    z = np.asarray(axis, dtype=float)
    z = z/np.linalg.norm(z)
    transverse = np.hypot(z[0], z[1])
    x = np.array([1., 0., 0.]) if transverse < 1.e-12 else np.array([z[1], -z[0], 0.])/transverse
    return np.stack((x, np.cross(z, x), z))


def sky_coordinates(position: np.ndarray, basis: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Longitude and latitude in degrees in the supplied orthonormal sky basis."""
    rotated = position @ basis.T
    radius = np.linalg.norm(rotated, axis=1)
    if np.any(radius <= 0):
        raise ValueError("Sky directions require nonzero observer-relative positions")
    return np.rad2deg(np.arctan2(rotated[:, 1], rotated[:, 0])) % 360., np.rad2deg(np.arcsin(np.clip(rotated[:, 2]/radius, -1, 1)))


def observed_redshift(position: np.ndarray, velocity: np.ndarray, z_cos: np.ndarray) -> np.ndarray:
    """First-order PINOCCHIO Doppler convention for proper peculiar km/s."""
    radial_velocity = np.sum(position*velocity, axis=1)/np.linalg.norm(position, axis=1)
    return z_cos + (1+z_cos)*radial_velocity/SPEED_OF_LIGHT_KM_S


@dataclass(frozen=True)
class NativeHaloInput:
    """Host arrays in canonical PINOCCHIO units, with explicit provenance."""

    values: dict[str, np.ndarray]
    metadata: dict
    particle_mass: float
    mean_density: float
    basis: np.ndarray


def load_native_halos(path: str | Path) -> NativeHaloInput:
    """Read a staged native PLC and audit group mass and unique occurrence IDs."""
    with h5py.File(path) as handle:
        values = {name: np.asarray(dataset) for name, dataset in handle["halos"].items()}
        metadata = json.loads(handle.attrs["metadata_json"])
    params = metadata["parameters"]
    if metadata["mass_unit"] != "Msun/h":
        raise ValueError("Staged mass units must explicitly be Msun/h")
    h, omega = float(params["Hubble100"][0]), float(params["Omega0"][0])
    box = float(params["BoxSize"][0]) * (1 if "BoxInH100" in params else h)
    grid = int(params["GridSize"][0])
    density = PINOCCHIO_RHO_CRIT*omega
    particle_mass = density*(box/grid)**3
    numbers = values["M_PIN"]/particle_mass
    rounded = np.rint(numbers)
    if np.any(np.abs(numbers-rounded) > 2.e-6*np.maximum(numbers, 1)):
        raise ValueError("Native mass is inconsistent with PINOCCHIO integer particle counts")
    if np.any(rounded < int(params["MinHaloMass"][0])):
        raise ValueError("Native halo violates the simulation's MinHaloMass")
    if len(np.unique(values["occurrence_id"])) != len(numbers):
        raise ValueError("Duplicate lightcone occurrence IDs")
    if any(not np.all(np.isfinite(value)) for value in values.values()):
        raise ValueError("Non-finite native PLC value")
    basis = cone_basis([float(x) for x in params["PLCAxis"]])
    native_lon = np.deg2rad(values["phi_native_deg"])
    native_lat = np.deg2rad(values["theta_native_deg"])
    native_unit = np.column_stack((np.cos(native_lat)*np.cos(native_lon),
                                   np.cos(native_lat)*np.sin(native_lon), np.sin(native_lat)))
    inferred_unit = values["position"] @ basis.T / np.linalg.norm(values["position"], axis=1)[:, None]
    # A longitude residual is ill-conditioned at a pole; compare directions.
    angular_error = np.linalg.norm(native_unit-inferred_unit, axis=1)
    # Native acos near the axis loses precision when its dot product is float32.
    if np.max(angular_error, initial=0) > 1.e-4:
        raise ValueError("PLC angular columns do not match its declared cone basis")
    native_z = observed_redshift(values["position"], values["velocity"], values["z_cos"])
    if np.max(np.abs(native_z-values["z_obs_native"]), initial=0) > 2.e-6:
        raise ValueError("Native observed redshift or velocity convention is inconsistent")
    metadata["native_audit"] = dict(
        max_direction_chord_residual=float(np.max(angular_error, initial=0)),
        max_observed_redshift_residual=float(np.max(np.abs(native_z-values["z_obs_native"]), initial=0)),
    )
    values["particle_count"] = rounded.astype(np.int64)
    return NativeHaloInput(values, metadata, particle_mass, density, basis)


def sample_colours(magnitude, redshift, is_central, rng, hodpy_root):
    """Sample the upstream conditional colour mixture using an explicit RNG.

    Returns colour, mixture membership and conditional red probability.
    Rest frame is z_ref=0.1. No colour clipping changes the Gaussian model.
    """
    model = hodpy_modules(hodpy_root)["colour"].Colour()
    red_sat = model.probability_red_satellite(magnitude, redshift)
    fraction_central = model.fraction_central(magnitude, redshift)
    blue_central = (model.fraction_blue(magnitude, redshift)-(1-red_sat))/fraction_central + (1-red_sat)
    probability = np.where(is_central, 1-blue_central, red_sat)
    # Upstream's comparison to a uniform deviate implicitly saturates these.
    probability = np.clip(probability, 0., 1.)
    is_red = rng.random(len(magnitude)) < probability
    mean = np.where(is_red, model.red_mean(magnitude, redshift), model.blue_mean(magnitude, redshift))
    width = np.where(is_red, model.red_rms(magnitude, redshift), model.blue_rms(magnitude, redshift))
    if np.any(width <= 0) or np.any(~np.isfinite(mean+width+probability)):
        raise ValueError("Hodpy colour model invalid at generated magnitude/redshift")
    return mean+width*rng.standard_normal(len(magnitude)), is_red, probability, mean, width
